


server:
  port: 8080
  context-path: /
jasypt:
  encryptor:
    password: 123456
spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    name: test
    url: jdbc:mysql://121.201.108.8:3306/hzdbtest
    username: admin
    password: ENC(TVDrvtye9u0enpIC5F1RN56/Swq1CUH3)
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

#  thymeleaf:
#    prefix: classpath:/templates/ #添加路径前缀

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.hz.domain  # 注意：对应实体类的路径
#  config-location: classpath:mybatis.xml


shiro:
  realm-class: com.hz.shiro.UserRealm
  custom-authc-filter-class: com.hz.shiro.AjaxAuthorizationFilter
  login-url: /api/sys/login
  success-url: /userList
  retry-max: 5
  retry-expire-time-redis: 5
  authorization-expire-time-redis: 10
  hash-iterations: 1024
  hash-algorithm-name: MD5
  stored-credentials-hex-encoded: false
  session:
    global-session-timeout: 1800000
    validation-interval: 100000
    validation-scheduler-enabled: true
  filter-chain-definitions:
    /static/**: anon
    /api/**: authc
    /test/**: authc
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

img:
#  location: /work/web/imgfile
#  url: http://121.201.108.9:18083
  location: D:/upload/
  url: http://192.168.0.178:8000